language: objective-c
matrix:
  include:
    - env:
        - config="KitsExample"
        - workspace="KitsExample.xcworkspace"
      osx_image: xcode7.3
      script:
        - cd Example/KitsExample
        - pod install
        - echo "Building for config=${config}"
        - xctool -workspace "${workspace}" -scheme "${config}" -sdk iphonesimulator
    - env:
        - config="iOS7_Example"
        - workspace="Example.xcworkspace"
      osx_image: xcode7.3
      script:
        - cd Example
        - pod install
        - echo "Building for config=${config}"
        - xctool test -workspace "${workspace}" -scheme "${config}" -sdk iphonesimulator
    - env:
        - config="iOS_Example"
        - workspace="Example.xcworkspace"
      osx_image: xcode7.3
      script:
        - cd Example
        - pod install
        - echo "Building for config=${config}"
        - xctool test -workspace "${workspace}" -scheme "${config}" -sdk iphonesimulator
    - env:
        - config="tvOS_Example"
        - workspace="Example.xcworkspace"
      osx_image: xcode7.3
      script:
        - cd Example
        - pod install
        - echo "Building for config=${config}"
        - xctool test -workspace "${workspace}" -scheme "${config}" -sdk appletvsimulator
    - env:
        - config="CarthageExample"
      osx_image: xcode7.3
      script:
        - cd Example/CarthageExample
        - echo "git \"$TRAVIS_BUILD_DIR\" \"$TRAVIS_BRANCH\"" > Cartfile
        - carthage update
        - echo "Building for config=${config}"
        - xctool -scheme "${config}" -sdk iphonesimulator
