language: objective-c
matrix:
  include:
    - env:
        - config="iOS7_Example"
        - workspace="Example.xcworkspace"
      osx_image: beta-xcode6.1
      script:
        - echo "Updating tools"
        - rvm use system
        - sudo gem install cocoapods
        - cd Example
        - pod install
        - echo "Building for config=${config}"
        - xctool test -workspace "${workspace}" -scheme "${config}" -sdk iphonesimulator
    - env:
        - config="iOS_Example"
        - workspace="Example.xcworkspace"
      osx_image: xcode7.3
      script:
        - cd Example
        - pod install
        - echo "Building for config=${config}"
        - xctool test -workspace "${workspace}" -scheme "${config}" -sdk iphonesimulator
    - env:
        - config="tvOS_Example"
        - workspace="Example.xcworkspace"
      osx_image: xcode7.3
      script:
        - cd Example
        - pod install
        - echo "Building for config=${config}"
        - xctool test -workspace "${workspace}" -scheme "${config}" -sdk appletvsimulator
